export enum MessageType {
  SYNC_START_REQUEST = 'SYNC_START_REQUEST',
  SYNC_READY_FOR_CLIENT_DATA = 'SYNC_READY_FOR_CLIENT_DATA',

  CLIENT_PATIENT_EXPORT = 'CLIENT_PATIENT_EXPORT',
  SERVER_CLIENT_EXPORT_COMPLETED = 'SERVER_CLIENT_EXPORT_COMPLETED',

  SERVER_REQUEST_MEASURES = 'SERVER_REQUEST_MEASURES',
  CLIENT_MEASURES_EXPORT = 'CLIENT_MEASURES_EXPORT',
  SERVER_MEASURES_COMPLETED = 'SERVER_MEASURES_COMPLETED',

  SERVER_PATIENT_IMPORT = 'SERVER_PATIENT_IMPORT',
  CLIENT_ACK_SERVER_PATIENT = 'CLIENT_ACK_SERVER_PATIENT',

  SERVER_REQUEST_CACHE_MANIFEST = 'SERVER_REQUEST_CACHE_MANIFEST',
  CLIENT_CACHE_MANIFEST = 'CLIENT_CACHE_MANIFEST',
  SERVER_REFERENCE_REGISTRY = 'SERVER_REFERENCE_REGISTRY',
  CLIENT_REGISTRY_ACK = 'CLIENT_REGISTRY_ACK',

  SERVER_TASK_IMPORT = 'SERVER_TASK_IMPORT',
  CLIENT_ACK_TASK_IMPORT = 'CLIENT_ACK_TASK_IMPORT',

  SERVER_REQUEST_TASK_RESULTS = 'SERVER_REQUEST_TASK_RESULTS',
  CLIENT_TASK_RESULT_EXPORT = 'CLIENT_TASK_RESULT_EXPORT',
  SERVER_TASK_RESULT_COMPLETED = 'SERVER_TASK_RESULT_COMPLETED',

  SYNC_PROCESS_COMPLETED = 'SYNC_PROCESS_COMPLETED',
  ERROR = 'ERROR',
  CLIENT_DISCONNECTED = 'CLIENT_DISCONNECTED',
}
