import { MarkdownStyle } from 'react-native-enriched-markdown';

const light = {
  foreground: '#2D2D3A',
  muted: '#6B6B85',
  accent: '#4A90D9',
  surface: '#FFFFFF',
  surfaceSecondary: '#F2F2F5',
  surfaceTertiary: '#EBEBEF',
  border: '#E3E3E8',
  success: '#4CAF82',
  danger: '#E05252',
  snow: '#FAFAFA',
};

const dark = {
  foreground: '#F5F5F7',
  muted: '#A0A0B8',
  accent: '#4A90D9',
  surface: '#2D2D3A',
  surfaceSecondary: '#363645',
  surfaceTertiary: '#3A3A4A',
  border: '#3A3A4A',
  success: '#4CAF82',
  danger: '#C94040',
  snow: '#FAFAFA',
};

const font = {
  body: 'Lato-Regular',
  bold: 'Lato-Bold',
  black: 'Lato-Black',
  boldItalic: 'Lato-BoldItalic',
  mono: 'Lato-Light',
};

function buildStyle(c: typeof light): MarkdownStyle {
  return {
    paragraph: {
      fontFamily: font.body,
      fontSize: 14,
      color: c.foreground,
      lineHeight: 22,
      marginTop: 0,
      marginBottom: 10,
      textAlign: 'left',
    },
    h1: {
      fontFamily: font.black,
      fontSize: 22,
      color: c.foreground,
      lineHeight: 30,
      marginTop: 20,
      marginBottom: 8,
      textAlign: 'left',
    },
    h2: {
      fontFamily: font.bold,
      fontSize: 18,
      color: c.foreground,
      lineHeight: 26,
      marginTop: 16,
      marginBottom: 6,
      textAlign: 'left',
    },
    h3: {
      fontFamily: font.boldItalic,
      fontSize: 16,
      color: c.foreground,
      lineHeight: 24,
      marginTop: 14,
      marginBottom: 4,
      textAlign: 'left',
    },
    h4: {
      fontFamily: font.bold,
      fontSize: 14,
      color: c.foreground,
      lineHeight: 22,
      marginTop: 12,
      marginBottom: 4,
      textAlign: 'left',
    },
    h5: {
      fontFamily: font.bold,
      fontSize: 13,
      color: c.muted,
      lineHeight: 20,
      marginTop: 10,
      marginBottom: 4,
      textAlign: 'left',
    },
    h6: {
      fontFamily: font.bold,
      fontSize: 12,
      color: c.muted,
      lineHeight: 18,
      marginTop: 8,
      marginBottom: 4,
      textAlign: 'left',
    },
    strong: {
      fontFamily: font.bold,
      fontWeight: 'normal',
    },
    em: {
      fontFamily: font.body,
      fontStyle: 'italic',
    },
    strikethrough: {
      color: c.muted,
    },
    underline: {
      color: c.accent,
    },
    link: {
      fontFamily: font.body,
      color: c.accent,
      underline: true,
    },
    blockquote: {
      fontFamily: font.body,
      fontSize: 14,
      color: c.muted,
      lineHeight: 22,
      marginTop: 4,
      marginBottom: 10,
      borderColor: c.accent,
      borderWidth: 3,
      gapWidth: 10,
      backgroundColor: c.surfaceSecondary,
    },
    list: {
      fontFamily: font.body,
      fontSize: 14,
      color: c.foreground,
      lineHeight: 22,
      marginTop: 0,
      marginBottom: 10,
      bulletColor: c.accent,
      bulletSize: 5,
      markerColor: c.accent,
      markerFontWeight: 'bold',
      gapWidth: 8,
      marginLeft: 4,
    },
    codeBlock: {
      fontFamily: font.mono,
      fontSize: 13,
      color: c.foreground,
      lineHeight: 20,
      marginTop: 4,
      marginBottom: 10,
      backgroundColor: c.surfaceTertiary,
      borderColor: c.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 12,
    },
    code: {
      fontFamily: font.mono,
      fontSize: 13,
      color: c.danger,
      backgroundColor: c.surfaceSecondary,
      borderColor: c.border,
    },
    thematicBreak: {
      color: c.border,
      height: 1,
      marginTop: 16,
      marginBottom: 16,
    },
    table: {
      fontFamily: font.body,
      fontSize: 13,
      color: c.foreground,
      lineHeight: 20,
      marginTop: 4,
      marginBottom: 12,
      headerFontFamily: font.bold,
      headerBackgroundColor: c.surfaceSecondary,
      headerTextColor: c.foreground,
      rowEvenBackgroundColor: c.surface,
      rowOddBackgroundColor: c.surfaceTertiary,
      borderColor: c.border,
      borderWidth: 1,
      borderRadius: 8,
      cellPaddingHorizontal: 12,
      cellPaddingVertical: 8,
    },
    taskList: {
      checkedColor: c.success,
      borderColor: c.border,
      checkboxSize: 16,
      checkboxBorderRadius: 4,
      checkmarkColor: c.snow,
      checkedTextColor: c.muted,
      checkedStrikethrough: true,
    },
    image: {
      height: 200,
      borderRadius: 8,
      marginTop: 4,
      marginBottom: 10,
    },
    inlineImage: {
      size: 18,
    },
    math: {
      fontSize: 14,
      color: c.foreground,
      backgroundColor: c.surfaceSecondary,
      padding: 12,
      marginTop: 4,
      marginBottom: 10,
      textAlign: 'center',
    },
    inlineMath: {
      color: c.accent,
    },
  };
}

export const lightStyle: MarkdownStyle = buildStyle(light);
export const darkStyle: MarkdownStyle = buildStyle(dark);
