name: Publish Beta Release & Build APK

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

env:
  ARTIFACT_NAME: app-beta.apk
  EAS_GITHUB_APP_NAME: ${{ github.event.repository.name }}
  EAS_GITHUB_PROJECT_ID: ${{ vars.EAS_PROJECT_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: ⚙️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: ⚙️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ⚙️ Setup Expo & EAS CLI
 
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: bun install

      - name: 🏷️ Extract tag
        id: tag
        run: |
          TAG=$(echo ${GITHUB_REF#refs/tags/})
          echo "TAG=$TAG" >> $GITHUB_ENV


      - name: 📝 Update version in package.json
        run: |
          sed -i "s|\"version\": \".*\"|\"version\": \"$TAG\"|" package.json
          bun install --lockfile-only

      - name: 📝 Update version in app.config.ts
        run: |
          sed -i "s|version: '[^\']*'|version: '$TAG'|" app.config.ts
          

      - name: 📜 Generate changelog
        run: bun run scripts/generate-changelog.mjs

      - name: 💾 Commit changes locally (Version Bump & Changelog)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json app.config.ts CHANGELOG.md
          
          if git diff --staged --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "chore: bump version to $TAG and update changelog"
            echo "✅ Changes committed locally (Le build sera basé sur ces changements)"
          fi

      
      - name: 🛠️ Build APK locally with EAS
        run: eas build --profile preview --platform android --non-interactive
        
      - name: Download AAB 
        run: curl -L -o ${{ env.ARTIFACT_NAME }}  "$(eas build:list --platform android --limit 1 --status finished --non-interactive | grep 'https://.*.apk' -o)"


      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Pre-release ${{ env.TAG }}
          body_path: CHANGELOG.md  
          draft: false
          prerelease: true
          files: |
            ${{ env.ARTIFACT_NAME }} # L'APK généré localement
            package.json
            app.config.ts
            CHANGELOG.md